/* Copyright (c) 2021-2024 by Inoland */

#pragma once

#include "NativeGameplayTags.h"

namespace InoLogCategory
{
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unkown)
	
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pawn)
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character)
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameMode)
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PlayerController)
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PlayerState)
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameState)
	
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InoEssentials)
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InoOss)
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InoUI)
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InoModal)
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InoNotif)
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InoLoading)
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InoBridge)
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InoInteraction)
}