/* Copyright (c) 2021-2024 by Inoland */

#pragma once

#include "NativeGameplayTags.h"

namespace InoLogTypes
{
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unkown)
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Info)
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Success)
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Warning)
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error)
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Critital)
}

namespace InoLogCategory
{
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unkown)
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InoEssentials)
	INOESSENTIALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InoOss)
}